version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/Berlin"
    rebase-strategy: disabled
    labels:
      - "dependencies"
      - "automerge"
      - "kodiak: merge.method = 'squash'"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "browserslist"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
