version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Europe/Berlin"
    rebase-strategy: disabled
    labels:
      - "dependencies"
      - "automerge"
      - "kodiak: merge.method = 'squash'"
    ignore:
      # Need to wait until every plugin support eslint 9
      #
      # It also dropped support for .eslintrc file in favor of flat config
      # Which means that we might need to completely rewrite/restructure our config
      #
      # ref: https://eslint.org/docs/latest/use/configure/migration-guide
      #
      - dependency-name: eslint
        versions:
          - '>= 9'

      # eslint-plugin-jest have a hard dependency on @typescript-eslint/utils@v6
      - dependency-name: @typescript-eslint/eslint-plugin
        versions:
          - '> 6'
      - dependency-name: @typescript-eslint/parser
        versions:
          - '> 6'
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "browserslist"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
