_extends: repo-settings
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - 'ci/circleci: check'
          - 'ci/circleci: lint'

labels:
  - name: "kodiak: merge.method = 'squash'"
    color: '#ffa500'
    description: Squash PR when merging
