# https://yarnpkg.com/configuration/yarnrc
nodeLinker: node-modules

unsafeHttpWhitelist:
  - localhost

changesetIgnorePatterns:
  - '.*'
  - '**/package.json'
  - yarn.lock
  - '**/*.test.{js,ts}'

changesetBaseRefs:
  - 'v0.1.6'
