# https://yarnpkg.com/configuration/yarnrc
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

unsafeHttpWhitelist:
  - localhost

changesetIgnorePatterns:
  - '.*'
  - package.json
  - yarn.lock
  - '**/*.test.{js,ts}'

changesetBaseRefs:
  - 'v0.1.5'
